name: Test

on:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make csvs dir
        run: mkdir ./csvs
      - uses: cardinalby/google-api-fetch-token-action@v1
        id: fetch_token
        with:
          clientId: ${{ secrets.G_API_CLIENT_ID }}
          clientSecret: ${{ secrets.G_API_CLIENT_SECRET }}
          refreshToken: ${{ secrets.G_API_REFRESH_TOKEN }}
      - name: Pull GSheet data
        id: sheet_to_csv
        env:
          API_KEY: ${{ secrets.G_API_KEY }}
          TOKEN: ${{ steps.fetch_token.outputs.accessToken }}
          CSV_DIR: ./csvs
          SHEETS: '[{"id":"1isczfU4EgpWYVbp9FuzqxrNFImmknD4wMPSj4it8uoQ","start":"A1","end":"E2","name":"temp"},{"id":"1isczfU4EgpWYVbp9FuzqxrNFImmknD4wMPSj4it8uoQ","start":"A1"},{"id":"1isczfU4EgpWYVbp9FuzqxrNFImmknD4wMPSj4it8uoQ","start":"A1","end":"E2","name":"temp"}]'
        run: ./print-csv.sh "$SHEETS"
      - name: Print csv
        working-directory: ./csvs
        run: |
          echo "This is one csv:"
          cat 0.csv
          echo "This is another:"
          cat 2.csv

